@startuml
title Diagrama de Seqüència – Pujada de Vídeos (Administrador)

actor Administrador
participant "Escriptori Admin" as AdminUI
participant "ExpressJS" as Express
participant "Spring Boot" as Spring
participant "Odoo" as Odoo
participant "PostgreSQL" as PG
participant "MySQL" as MySQL
participant "MongoDB" as Mongo
participant "App mobil" as App
Administrador -> AdminUI : Accedix a la plataforma
AdminUI -> Odoo : Inici de sessió
Odoo -> PG : Validacio
PG -> Odoo : Tot be
Odoo -> AdminUI : Tot be + token
Administrador -> AdminUI : Selecciona pujar video
AdminUI -> AdminUI : Valida formulari (titol, serie, idioma)
AdminUI -> Odoo : Valida token i rol administrador (JWT)
Odoo -> PG : Comprova usuari, rol i permisos
PG --> Odoo : Validacio correcta
Odoo --> AdminUI : Tot correcte

AdminUI -> Express : Envia fitxer de video
Express -> Express : Desa video original

Express -> Express : Transcodifica video
Express -> Express : Genera segments HLS
Express -> Express : Genera playlist m3u8

Express --> AdminUI : Video processat + metadades
AdminUI -> Spring : Metadades + Dades video
Spring -> MySQL : Desa dades basiques
MySQL --> Spring : OK

Spring -> Mongo : Desa metadades
Mongo --> Spring : OK

Spring --> AdminUI : Video publicat
Spring -> App : Notifica nou contingut

@enduml